spring:
  datasource:
    url: jdbc:h2:mem:memh2
    driver-class-name: org.h2.Driver
    username: sa
    password: sa
    initialization-mode: always
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate.ddl-auto: none
    hibernate.use-new-id-generator-mappings: false
  h2:
    console:
      enabled: true